name: Deploy Angular App

on:
  workflow_dispatch: # manueller Start
  push:
    branches:
      - main
  workflow_call: # nur als Einstiegspunkt für andere Workflows, kein eigenes Secret nötig

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0         # vollständige Git-Historie
            persist-credentials: true  # erlaubt Push über das Actions-Token

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build -- --configuration production --base-href "/fantasy-app/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/fantasy-league-custom-frontend/browser
